#!/bin/sh
if [ "$1" = "upgrade" ] || [ "$1" = "install" ] || [ "$1" = "configure" ]; then
    # Standard check for sbreload / killall to notify package managers to prompt for respring
    if [ -x /usr/bin/sbreload ]; then
        sbreload
    elif [ -x /usr/libexec/sbreload ]; then
        /usr/libexec/sbreload
    else
        killall -9 SpringBoard
    fi
fi
exit 0
