#!/bin/sh
if [ "$1" = "remove" ] || [ "$1" = "purge" ]; then
    if [ -x /usr/bin/sbreload ]; then
        sbreload
    elif [ -x /usr/libexec/sbreload ]; then
        /usr/libexec/sbreload
    else
        killall -9 SpringBoard
    fi
fi
exit 0
